packages:
  # Include all of the core configuration
  core: !include sonoff-powr316.yaml

esphome:
  # This will allow for project identification,
  # configuration and updates.
  project:
    name: diekruecke.sonoff-powr316
    version: dev # This will be replaced by the github workflows with the `release` version

# This should point to the public location of the yaml file that will be adopted.
# In this case it is the core yaml file that does not contain the extra things
# that are provided by this factory yaml file as the user does not need these once adopted.
dashboard_import:
  package_import_url: github://diekruecke/sonoff-powr316/sonoff-powr316.yaml@main

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none
